apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: container-health
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/bruno-diaz-dev/gitops-aks-platform.git
    targetRevision: main
    path: ./apps/container-health

  destination:
    server: https://kubernetes.default.svc
    namespace: container-health

  syncPolicy:
    automated:
      prune: true
      selfHeal: true